
name: linter-check

on:
  push

jobs:
  my-job:
    runs-on: ubuntu-latest
    steps:
        # Check-out repository under GitHub workspace
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0 # important!
      - name: Setup PHP
        # Action gives to setup the PHP environment to test application
        uses: shivammathur/setup-php@v2
        with:
          # Specify the PHP version
          php-version: '7.4'
      - name: Install PHP_CodeSniffer
        run: |
          curl -OL https://squizlabs.github.io/PHP_CodeSniffer/phpcs.phar
          php phpcs.phar --version
      - uses: tinovyatkin/action-php-codesniffer@v1
        with:
          files: "**.php" # you may customize glob as needed
          phpcs_path: php phpcs.phar
          standard: phpcs.xml
      - name: Install
        # Install project (Composer)
        run: make install
      - name: Linter check
        run: make lint
