
name: linter-check

on:
  push

jobs:
  my-job:
    runs-on: ubuntu-latest
    steps:
      - name: Linter check
        run: make lint
      - name: Install
        # Install project (Composer)
        run: make install